In [65]:
import numpy as np
x=np.random.random((3,1))
print("x:",x)
y=np.random.random((1,))
print("y:",y)
z=np.maximum(x,y)
print("Z:",z)

x: [[0.73414285]
 [0.77352862]
 [0.17295972]]
y: [0.63294588]
Z: [[0.73414285]
 [0.77352862]
 [0.63294588]]


^obviously extends the y-Tensor to an 2Dimensional Tensor and finds the maximum of x and y in every element 

In [ ]:
def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0]
    z=0.
    for i in range(x.shape[0]):
        z+=x[i]*y[i]
    return z

x=np.random.random((1,3))
y=np.random.random((3,))
    
naive_vector_dot(x,y)

In [190]:
def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0]
    z=0.
    for i in range(x.shape[0]):
        z+=x[i]*y[i]
    return z

def naive_matrix_vector_dot(x,y):
    z=np.zeros(x.shape[0])
    print("z:",z)
    for i in range(x.shape[0]):
        z[i]=naive_vector_dot(x[i,:],y)
        print("z[i]",z)
        print("x[i]:",x[i,:])
    return z
x=np.random.random((1,3))
print("x:",x)

y=np.random.random((3,))
print("x[i]:",x[0,:],y)
print("y:",y)
z=naive_matrix_vector_dot(x,y)
print(z)


x: [[0.27016872 0.75429515 0.45329484]]
x[i]: [0.27016872 0.75429515 0.45329484] [0.50083613 0.56175292 0.96160029]
y: [0.50083613 0.56175292 0.96160029]
z: [0.]
z[i] [0.9949262]
x[i]: [0.27016872 0.75429515 0.45329484]
[0.9949262]


In [181]:
x=np.random.random((1,3))
y=np.random.random((3,))
print(x)
print("---")
print(y)
print("---")
assert len(x.shape)==1
print("---")
print(len(y.shape))
print("---")
for i in range(x.shape[0]):
        z[i]=naive_vector_dot(x[i,:],y)
        print("z[i]",z[i])



[[0.58678397 0.48846123 0.39597964]]
---
[0.90747158 0.10902006 0.11562427]
---


AssertionError: 

In [7]:
import numpy as np
x=np.random.random((2))
y=np.random.random((2))
print(x)
print(y)
def vec_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0]
    z=0
    for i in range (x.shape[0]):
        z+=x[i]*y[i]
    return z
vec_dot(x,y)

[0.29051832 0.81618843]
[0.79546726 0.54950084]


0.6795940385442218

^will return the dot product of two vectors, if both have 1 dimension

In [14]:
import numpy as np
x=np.random.random((2,2))
y=np.random.random((2))
print(x)
print(y)
def matrix_vec_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1]==y.shape[0]
    z=np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i]+=x[i,j]*y[j]

    return z
matrix_vec_dot(x,y)

[[0.2302851  0.93501995]
 [0.83664664 0.40556493]]
[0.84415706 0.82583329]


array([0.9665674 , 1.04119019])

In [17]:
def vec_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0]
    z=0
    for i in range (x.shape[0]):
        z+=x[i]*y[i]
    return z

def matrix_vec_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==2
    assert x.shape[1]==y.shape[0]

    z=np.zeros((x.shape[0],y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x=x[i,:]
            column_y=y[:,j]
            z[i,j]=vec_dot(row_x,column_y)
    return z

x=np.random.random((2,2))
y=np.random.random((2,2))
matrix_vec_dot(x,y)

array([[0.6592466 , 0.98150331],
       [0.77981049, 0.91043209]])

^zwei matrizen miteinander verrechnen

In [25]:
x=np.random.random((2,3))
print(x.shape)
print(x)
x=x.reshape((3,2))
print(x.shape)
print(x)
x=x.reshape((6,1))
print(x.shape)
print(x)
x=x.transpose()
print(x.shape)
print(x)

(2, 3)
[[0.81075218 0.30596367 0.71436839]
 [0.7322216  0.67640638 0.66316254]]
(3, 2)
[[0.81075218 0.30596367]
 [0.71436839 0.7322216 ]
 [0.67640638 0.66316254]]
(6, 1)
[[0.81075218]
 [0.30596367]
 [0.71436839]
 [0.7322216 ]
 [0.67640638]
 [0.66316254]]
